### ISSUE TITLE
send message when Enter key press 

### ISSUE THREAD

**Issue by bingbing720** [johniak/react-web-gifted-chat#13]
How to configure gift-chat to send message when enter key is pressed?

**Comment by Aleksandr09332** [comment]
I also have problems with it

**Comment by simplepry-s** [comment]
+1 can anyone help

**Comment by simplepry-s** [comment]
@johniak please help

**Comment by johniak** [comment]
Oki, I will fix it on monday. I don’t have computer with me right now...

**Comment by simplepry-s** [comment]
> Oki, I will fix it on monday. I don’t have computer with me right now...

@johniak thank you but it possible to 
when keypress enter = send message
When keypress shift + enter = new line message

**Comment by simplepry-s** [comment]
@johniak thank you

**Comment by simplepry-s** [comment]
> Oki, I will fix it on monday. I don’t have computer with me right now...

Hi @johniak please help 😭

**Comment by johniak** [comment]
I released new version with this functionality
check v0.6.7

**Comment by iswetak** [comment]
Hi @johniak please help
How to configure gift-chat to send message when enter key is pressed?

**Comment by HamzaTatheer** [comment]
Hi @johniak , gift chat still does not send message with enter. Can you please update if it works or not
