### ISSUE TITLE
Can't resolve 'react-web-gifted-chat'

### ISSUE THREAD

**Issue by selyon** [johniak/react-web-gifted-chat#8]
I get this error when i start the example application

`Can't resolve 'react-web-gifted-chat in ./src/App.js`

Steps to Reproduce
- Download package from github
- open terminal and go to the example folder
- yarn
- yarn start

**Comment by selyon** [comment]
I managed to make the example app work, i modified the package.json, removed this line
`"react-web-gifted-chat": "file:../",`
then i installed gifted-chat inside the example app as normal, using yarn.

Now when i start the app, only on Firefox (64.0.2 (64 bit)), it gives me this error
`css2properties doesn't have an indexed property setter for '0'`
everytime it tries to render something clickable, like an image or the SEND button.
Tested on Chrome, Edge and Safari it works without any problem.

**Comment by johniak** [comment]
example is made to be able to use with whole repository
![image](https://user-images.githubusercontent.com/1036376/51733221-f3d16580-2080-11e9-957f-6187d122e58a.png)
I will check the problem with firefox

**Comment by johniak** [comment]
About firefox error somewhere in code propably exist react-native way of merge styles with array

**Comment by johniak** [comment]
Firefox issue is fixed in v0.6.3

**Comment by selyon** [comment]
The problem is still present when it tries to render the send button:
The above error occurred in the < div> component:

- in div (created by TouchableOpacity)
- in TouchableOpacity (created by Send)
- in Send (created by InputToolbar)
- in div (created by View)
- in View (created by InputToolbar)
- in div (created by View)
- in View (created by InputToolbar)
- in InputToolbar (created by GiftedChat)
- in div (created by View)
- in View (created by GiftedChat)
- in GiftedChat (at App.js:25)
- in div (at App.js:24)
- in App (at src/index.js:7)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. index.js:1446
TypeError: CSS2Properties doesn't have an indexed property setter for '0'

**Comment by Inayat567** [comment]
what are the steps to reproduce the mentioned error @johniak 
I have tried to reproduce, But cannot on chrome, Edge, and firebox
